export const GlobalConstant = {
  loaderDuration: 2000,
  welcomeLoaderDuration: 3000,
  setTimeOutTwoHundred: 200,
  setTimeOutOneThousand: 1000,
  celebrationDuration: 7,
  titleOptions: [
    "Brilliant",
    "Wonderful",
    "Superb",
    "Fantastic",
    "Majestic",
    "Amazing",
  ],
  menuDailyFocus: "daily-focus",
  alertCancelButton: "alert-button-cancel",
  alertInputBox: "input-type-inputbox",
  alertType: "basic-alert",
  goalsWorksheetType: "GoalsWorksheet",
  journalDirection: "next",
  goalsUpdateTime: "golasUpdateTime",
  journalUpdateTime: "journalUpdateTime",
  menuUpdate: "Updated",
  tabName: "dashboard",
  menuDailyJournal: "dashboard_journal_item_text",
  menuGoals: "dashboard_goals_item_text",
  boostPqTitle: "Boost your PQ",
  boostPqThumbnail: "item-gym.png",
  toastDuration: 2000,
  defaultImage: "../assets/icon/default-image.png",
  community: "community",
};
